//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankalpMed.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Item
    {
        public long ItemId { get; set; }
        public string ItemName { get; set; }
        public decimal PurchasePrice { get; set; }
        public decimal SalePrice { get; set; }
        public int CatId { get; set; }
        public decimal ItemQty { get; set; }
        public string Unit { get; set; }
        public string Details { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public string Barcode { get; set; }
        public string HSN { get; set; }
        public string MFGComapny { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> Wprice { get; set; }
        public Nullable<decimal> WoutSalePrice { get; set; }
        public Nullable<System.DateTime> MFGDate { get; set; }
    }
}
