//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankalpMed.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer
    {
        public long CustId { get; set; }
        public string CustName { get; set; }
        public string Address { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Details { get; set; }
        public System.DateTime Date { get; set; }
        public int Status { get; set; }
        public string GST { get; set; }
        public string PAN { get; set; }
        public string Password { get; set; }
    }
}
