//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSankalpMed.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContactForm
    {
        public int ID { get; set; }
        public string ContactName { get; set; }
        public string ContactEmail { get; set; }
        public string ContactNo { get; set; }
        public string Message { get; set; }
    }
}
